# Generated by Django 5.1.1 on 2024-09-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0002_remove_tenant_active_remove_tenant_move_in_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcollection',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='description',
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='name',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(blank=True, default=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
