# Generated by Django 5.1.1 on 2024-09-24 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0003_remove_rentcollection_rent_remove_tenant_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcollection',
            name='total',
        ),
        migrations.AddField(
            model_name='tenant',
            name='unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental_management.unit'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='flat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental_management.flat'),
        ),
    ]
