# Generated by Django 5.1.1 on 2024-09-24 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0004_remove_rentcollection_total_tenant_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='unit',
        ),
        migrations.AddField(
            model_name='unit',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_management.flat'),
        ),
    ]
