# Generated by Django 5.1.1 on 2024-09-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0005_remove_flat_unit_unit_flat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='status',
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(blank=True, choices=[('occupied', 'Occupied'), ('vacant', 'Vacant')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='flat_number',
            field=models.CharField(max_length=15),
        ),
    ]
