# Generated by Django 5.1.1 on 2024-09-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0008_tenant_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcollection',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
