# Generated by Django 5.1.1 on 2024-09-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0010_alter_flat_flat_number_alter_tenant_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='is_active',
        ),
    ]
