# Generated by Django 5.1.1 on 2024-09-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0011_remove_tenant_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='rent',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='unit',
            name='flat',
        ),
    ]
